ARG IMAGE_PROXY_PREFIX=""
FROM ${IMAGE_PROXY_PREFIX}vegardit/softhsm2-pkcs11-proxy:latest AS pkcs11-proxy

FROM  ${BASE_IMAGE_TO_USE}

USER root
RUN apk update && apk add opensc openssl
COPY --from=pkcs11-proxy /usr/local/lib/libpkcs11-proxy* /usr/local/lib/
COPY --from=pkcs11-proxy /opt/test.tls.psk /opt/test.tls.psk
USER eidas-middleware

