DROP ALL OBJECTS;

CREATE TABLE BLACKLISTENTRY
(
  SECTORID         VARCHAR(255) NOT NULL,
  SPECIFICID       VARCHAR(255) NOT NULL,
  BLACKLISTVERSION BIGINT(19)   NOT NULL,
  PRIMARY KEY (SECTORID, SPECIFICID)
);

CREATE TABLE TERMINALPERMISSION
(
  REFID VARCHAR(255) NOT NULL,
  SECTORID BLOB NOT NULL,
  PRIMARY KEY (REFID)
);